// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElColorPicker: typeof import("element-plus/es")["ElColorPicker"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    LanguageSelect: typeof import("./src/components/LanguageSelect/LanguageSelect.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SIcon: typeof import("./src/components/SIcon/SIcon.vue")["default"];
    ThemeSelect: typeof import("./src/components/ThemeSelect/ThemeSelect.vue")["default"];
    ThemeSelectDrawer: typeof import("./src/components/ThemeSelect/ThemeSelectDrawer.vue")["default"];
    VIcon: typeof import("./src/components/VIcon/VIcon.vue")["default"];
  }
}

export {};
